#pragma once

namespace halo_interface
{
	class IGameEngine;
	class IDataAccess;
	class IGameEngineHost;

	struct s_game_options;
	struct s_library_settings;
}

enum e_game_engine_vtable
{
	_game_engine_vtable_dtor,
	_game_engine_vtable_InitializeAsDLL,
	_game_engine_vtable_PlayGame,
	_game_engine_vtable_unk_3,
	_game_engine_vtable_unk_4,
	_game_engine_vtable_unk_5,
	_game_engine_vtable_unk_6,
	_game_engine_vtable_unk_7,
	_game_engine_vtable_unk_8,
	_game_engine_vtable_unk_9,
	_game_engine_vtable_unk_10,
	k_number_of_game_engine_vtable_functions,
	k_game_engine_vtable_size = k_number_of_game_engine_vtable_functions * sizeof(uintptr_t)
};

enum e_game_engine_host_vtable
{
	_game_engine_host_vtable_dtor,
	_game_engine_host_vtable_unk_1,
	_game_engine_host_vtable_unk_2,
	_game_engine_host_vtable_unk_3,
	_game_engine_host_vtable_unk_4,
	_game_engine_host_vtable_unk_5,
	_game_engine_host_vtable_unk_6,
	_game_engine_host_vtable_unk_7,
	_game_engine_host_vtable_unk_8,
	_game_engine_host_vtable_unk_9,
	_game_engine_host_vtable_unk_10,
	_game_engine_host_vtable_unk_11,
	_game_engine_host_vtable_unk_12,
	_game_engine_host_vtable_unk_13,
	_game_engine_host_vtable_unk_14,
	_game_engine_host_vtable_unk_15,
	_game_engine_host_vtable_unk_16,
	_game_engine_host_vtable_unk_17,
	_game_engine_host_vtable_unk_18,
	_game_engine_host_vtable_unk_19,
	_game_engine_host_vtable_unk_20,
	_game_engine_host_vtable_unk_21,
	_game_engine_host_vtable_unk_22,
	_game_engine_host_vtable_unk_23,
	_game_engine_host_vtable_unk_24,
	_game_engine_host_vtable_unk_25,
	_game_engine_host_vtable_unk_26,
	_game_engine_host_vtable_unk_27,
	_game_engine_host_vtable_unk_28,
	_game_engine_host_vtable_unk_29,
	_game_engine_host_vtable_unk_30,
	_game_engine_host_vtable_unk_31,
	_game_engine_host_vtable_unk_32,
	_game_engine_host_vtable_unk_33,
	_game_engine_host_vtable_unk_34,
	_game_engine_host_vtable_unk_35,
	_game_engine_host_vtable_unk_36,
	_game_engine_host_vtable_unk_37,
	_game_engine_host_vtable_unk_38,
	_game_engine_host_vtable_unk_39,
	_game_engine_host_vtable_unk_40,
	_game_engine_host_vtable_transport_sendto_handler,
	_game_engine_host_vtable_unk_42,
	_game_engine_host_vtable_transport_recvfrom_handler,
	_game_engine_host_vtable_unk_44,
	_game_engine_host_vtable_unk_45,
	_game_engine_host_vtable_unk_46,
	_game_engine_host_vtable_unk_47,
	_game_engine_host_vtable_unk_48,
	_game_engine_host_vtable_unk_49,
	_game_engine_host_vtable_unk_50,
	_game_engine_host_vtable_unk_51,
	_game_engine_host_vtable_unk_52,
	_game_engine_host_vtable_unk_53,
	_game_engine_host_vtable_unk_54,
	_game_engine_host_vtable_unk_55,
	_game_engine_host_vtable_unk_56,
	_game_engine_host_vtable_unk_57,
	_game_engine_host_vtable_unk_58,
	_game_engine_host_vtable_unk_59,
	_game_engine_host_vtable_unk_60,
	_game_engine_host_vtable_unk_61,
	_game_engine_host_vtable_unk_62,
	_game_engine_host_vtable_unk_63,
	_game_engine_host_vtable_unk_64,
	_game_engine_host_vtable_unk_65,
	_game_engine_host_vtable_unk_66,
	_game_engine_host_vtable_unk_67,
	_game_engine_host_vtable_unk_68,
	_game_engine_host_vtable_unk_69,
	_game_engine_host_vtable_unk_70,
	_game_engine_host_vtable_unk_71,
	_game_engine_host_vtable_unk_72,
	_game_engine_host_vtable_unk_73,
	_game_engine_host_vtable_unk_74,
	_game_engine_host_vtable_unk_75,
	_game_engine_host_vtable_unk_76,
	_game_engine_host_vtable_unk_77,
	_game_engine_host_vtable_unk_78,
	_game_engine_host_vtable_unk_79,
	_game_engine_host_vtable_unk_80,
	_game_engine_host_vtable_unk_81,
	_game_engine_host_vtable_unk_82,
	_game_engine_host_vtable_unk_83,
	_game_engine_host_vtable_unk_84,
	_game_engine_host_vtable_unk_85,
	_game_engine_host_vtable_unk_86,
	_game_engine_host_vtable_unk_87,
	_game_engine_host_vtable_unk_88,
	_game_engine_host_vtable_unk_89,
	_game_engine_host_vtable_unk_90,
	_game_engine_host_vtable_unk_91,
	_game_engine_host_vtable_unk_92,
	_game_engine_host_vtable_unk_93,
	_game_engine_host_vtable_unk_94,
	_game_engine_host_vtable_unk_95,
	_game_engine_host_vtable_unk_96,
	_game_engine_host_vtable_unk_97,
	_game_engine_host_vtable_unk_98,
	_game_engine_host_vtable_unk_99,
	_game_engine_host_vtable_unk_100,
	_game_engine_host_vtable_unk_101,
	_game_engine_host_vtable_unk_102,
	_game_engine_host_vtable_unk_103,
	_game_engine_host_vtable_unk_104,
	_game_engine_host_vtable_unk_105,
	_game_engine_host_vtable_unk_106,
	_game_engine_host_vtable_unk_107,
	_game_engine_host_vtable_unk_108,
	_game_engine_host_vtable_unk_109,
	_game_engine_host_vtable_unk_110,
	_game_engine_host_vtable_unk_111,
	_game_engine_host_vtable_unk_112,
	_game_engine_host_vtable_unk_113,
	_game_engine_host_vtable_unk_114,
	_game_engine_host_vtable_unk_115,
	_game_engine_host_vtable_unk_116,
	_game_engine_host_vtable_unk_117,
	_game_engine_host_vtable_unk_118,
	_game_engine_host_vtable_unk_119,
	_game_engine_host_vtable_unk_120,
	k_number_of_game_engine_host_vtable_functions,
	k_game_engine_host_vtable_size = k_number_of_game_engine_host_vtable_functions * sizeof(uintptr_t)
};

using create_game_engine_t = uint32_t (*)(halo_interface::IGameEngine**);
using create_data_access_t = uint32_t (*)(halo_interface::IDataAccess**);
using set_library_settings_t = void (*)(halo_interface::s_library_settings*);

using transport_sendto_handler_t = int64_t (*)(halo_interface::IGameEngineHost*, uint64_t, uint8_t*, uint32_t, uint32_t);
using transport_recvfrom_handler_t = int64_t (*)(halo_interface::IGameEngineHost*, uint8_t*, uint32_t, uint64_t*, uint32_t);

using game_engine_play_game_t = void (*)(halo_interface::IGameEngine*, halo_interface::IGameEngineHost*, halo_interface::s_game_options*);
